// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gncvlmkjvxfatuiblbqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduY3ZsbWtqdnhmYXR1aWJsYnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTE2OTUsImV4cCI6MjA1Nzk4NzY5NX0.EtoNNIVL_MEDu5edYtM-ARa3boq33IEKR15AONC4BDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);